/**
 * Single point of update for all action types
 */
export const APP_LOAD = 'APP_LOAD';

export const GET_GEOJSON_START = 'GET_GEOJSON_START';
export const GET_GEOJSON_ERROR = 'GET_GEOJSON_ERROR';
export const GET_GEOJSON_COMPLETE = 'GET_GEOJSON_COMPLETE';

export const GET_VEHICLE_POSITIONS_START = 'GET_VEHICLE_POSITIONS_START';
export const GET_VEHICLE_POSITIONS_ERROR = 'GET_VEHICLE_POSITIONS_ERROR';
export const GET_VEHICLE_POSITIONS_COMPLETE = 'GET_VEHICLE_POSITIONS_COMPLETE';

export const SET_ROUTES_FOR_FILTER = 'SET_ROUTES_FOR_FILTER';
export const ADD_BLOCKED_ROUTE = 'ADD_BLOCKED_ROUTE';
export const REMOVE_BLOCKED_ROUTE = 'REMOVE_BLOCKED_ROUTE';

export const ADD_BLOCKED_MAP_OPTION = 'ADD_BLOCKED_MAP_OPTION';
export const REMOVE_BLOCKED_MAP_OPTION = 'REMOVE_BLOCKED_MAP_OPTION';


export default {
  APP_LOAD,
  GET_GEOJSON_START,
  GET_GEOJSON_ERROR,
  GET_GEOJSON_COMPLETE,
  GET_VEHICLE_POSITIONS_START,
  GET_VEHICLE_POSITIONS_ERROR,
  GET_VEHICLE_POSITIONS_COMPLETE,
  SET_ROUTES_FOR_FILTER,
  ADD_BLOCKED_ROUTE,
  REMOVE_BLOCKED_ROUTE,
  ADD_BLOCKED_MAP_OPTION,
  REMOVE_BLOCKED_MAP_OPTION
};
