export const APP_LOAD = 'APP_LOAD';

export const GET_GEOJSON_START = 'GET_GEOJSON_START';
export const GET_GEOJSON_ERROR = 'GET_GEOJSON_ERROR';
export const GET_GEOJSON_COMPLETE = 'GET_GEOJSON_COMPLETE';

export const GET_VEHICLE_POSITIONS_START = 'GET_VEHICLE_POSITIONS_START';
export const GET_VEHICLE_POSITIONS_ERROR = 'GET_VEHICLE_POSITIONS_ERROR';
export const GET_VEHICLE_POSITIONS_COMPLETE = 'GET_VEHICLE_POSITIONS_COMPLETE';

export const GET_ROUTES_FOR_FILTER = 'GET_ROUTES_FOR_FILTER';
export const GET_MAPOPTIONS_FOR_FILTER = 'GET_MAPOPTIONS_FOR_FILTER';


export default { 
    APP_LOAD, 
    GET_GEOJSON_START, 
    GET_GEOJSON_ERROR, 
    GET_GEOJSON_COMPLETE,
    GET_VEHICLE_POSITIONS_START,
    GET_VEHICLE_POSITIONS_ERROR,
    GET_VEHICLE_POSITIONS_COMPLETE,
    GET_ROUTES_FOR_FILTER,
    GET_MAPOPTIONS_FOR_FILTER
};