export const APP_LOAD = 'APP_LOAD';

export const GET_GEOJSON_START = 'GET_GEOJSON_START';
export const GET_GEOJSON_ERROR = 'GET_GEOJSON_ERROR';
export const GET_GEOJSON_COMPLETE = 'GET_GEOJSON_COMPLETE';


export default { 
    APP_LOAD, 
    GET_GEOJSON_START, 
    GET_GEOJSON_ERROR, 
    GET_GEOJSON_COMPLETE 
};